### ISSUE TITLE
fieldTypes folder should be lower case instead of camelCase

### ISSUE THREAD

**Issue by therealjustinlong** [rkingon/Craft-Plugin--Input-Mask#1]
/inputmask/fieldTypes should be renamed to /inputmask/fieldtypes to prevent certain php environments from not detecting the InputMask class.

**Comment by rkingon** [comment]
ugh, i actually did change that locally, but since osx is case insensitive it never picked it up.. anyways, fixed in: 445a1f117df9863035ccf69372c2b3cb73345a6c

thanks!
