### ISSUE TITLE
Masking does not work in a matrix field

### ISSUE THREAD

**Issue by idahotallpaul** [rkingon/Craft-Plugin--Input-Mask#2]
The input mask works fine when used as a standalone field, but when used in a matrix, the masking does not work.

**Comment by rkingon** [comment]
common problem with javascript & matrix. I have the same issue with: https://github.com/fruitstudios/Icons

I'll take a look at the matrix api and see if there are some javascript events that get fired in which we would re-init the javascript.

thanks for the heads up

**Comment by rkingon** [comment]
this is fixed in 6a94b89df56af59299816aa7c6a3d19f35389232

**Comment by idahotallpaul** [comment]
Awesome. Thanks for the quick response!
